# Generated by Django 3.2.5 on 2021-07-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='child_id',
        ),
    ]
